#! /bin/sh
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

theme="Multipart"
~/.config/polybar/$theme/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           8

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding 35

# border color
bspc config normal_border_color "#3b3f4c"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#e5c07b"
bspc config presel_feedback_color "#6272a4"

# movie and resize window with mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

########################################################
############       BSPC RULE       #####################
########################################################
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
# always floating gui for python
bspc rule -a Tk state=floating

xsetroot -cursor_name left_ptr &
