#! /bin/sh
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &

killall btops
btops &
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           9

bspc config split_ratio           0.51
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config focus_follows_pointer true
bspc config top_padding 31

# border color
bspc config normal_border_color "#3b3f4c"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color '#9cdcfe'
bspc config presel_feedback_color "#6272a4"

# movie and resize window with mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc config honor_size_hints true
bspc config ignore_ewh_struts polybar

########################################################
############       BSPC RULE       #####################
########################################################
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off

# always floating gui for python
bspc rule -a Tk -o state=floating
bspc rule -a PacketTracer -o state=floating
bspc rule -a Conky-manager -o state=floating

# bspc rule -a \* rectangle 800x600+0+0 center=true

xsetroot -cursor_name left_ptr &
