#! /bin/sh
bspc rule -r "*"

polybar=$(pgrep -x polybar > /dev/null && echo "Process found" || echo "Process not found")
if [[ $polybar == "Process not found" ]]; then
	~/.config/bspwm/src/start-polybar.sh &
fi

if [[ $(xrandr -q | grep 'HDMI') ]]; then
  killall btops
  xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI --mode 1920x1080 --rotate normal --right-of eDP1
  bspc monitor eDP -d 1 2 3 4 5
  bspc monitor HDMI-A-0 -d 6 7 8 9 10
else
  killall btops
  btops &
fi

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &

bspc config border_width         2
bspc config window_gap          10 

bspc config split_ratio           0.51
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config focus_follows_pointer true
bspc config top_padding 31

# border color
bspc config normal_border_color "#3b3f4c"
bspc config active_border_color "#bd93f9"

bspc config focused_border_color '#F92672'

bspc config presel_feedback_color "#6272a4"

# movie and resize window with mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
# bspc config pointer_action2 resize_corner
bspc config honor_size_hints true
# bspc config ignore_ewh_struts polybar

########################################################
############       BSPC RULE       #####################
########################################################
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off

# always floating gui for python
bspc rule -a Conky-manager state=floating
bspc rule -a Tk state=floating
bspc rule -a flameshot state=floating
bspc rule -a Messenger\ call\ -\ Brave rectangle=450x800+1400+50 state=floating

# bspc rule -a \* rectangle 800x600+0+0 center=true

# fix X cursor to default
xsetroot -cursor_name left_ptr &
